In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("weight-height.csv")
data.head(5)



Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
data.info

<bound method DataFrame.info of       Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]>

In [4]:
data.describe

<bound method NDFrame.describe of       Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]>

In [5]:
X = data.Height.values     
X

array([73.84701702, 68.78190405, 74.11010539, ..., 63.86799221,
       69.03424313, 61.94424588])

In [6]:
Y = data.Weight.values 
Y

array([241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
       163.85246135, 113.64910268])

In [7]:
x =  X.reshape(10000,-1)

In [8]:
x[0]

array([73.84701702])

In [9]:
print(x)
print(Y)

[[73.84701702]
 [68.78190405]
 [74.11010539]
 ...
 [63.86799221]
 [69.03424313]
 [61.94424588]]
[241.89356318 162.31047252 212.74085556 ... 128.47531878 163.85246135
 113.64910268]


In [10]:
X_train , Y_train = x[:8000] , Y[:8000]
X_test , Y_test = x[8000:] , Y[8000:]

print("Training : " ,len(X_train),len(Y_train))
print("Testing : " ,len(X_test),len(Y_test))

Training :  8000 8000
Testing :  2000 2000


# Use skitlearn pre-define function to split the data into test and train

In [11]:
X_train ,X_test, Y_train , Y_test = train_test_split(x ,Y ,test_size=0.2)
print("Training : " ,len(X_train),len(Y_train))
print("Testing : " ,len(X_test),len(Y_test))

Training :  8000 8000
Testing :  2000 2000


# Create ML model with sklearm

In [12]:
from sklearn.linear_model import LinearRegression


In [13]:
lr = LinearRegression()

# Training data as input and output

In [14]:
lr.fit(X_train,Y_train)

LinearRegression()

# predict on unscean data`

In [15]:
y_pred = lr.predict(X_test)
print(len(y_pred))
y_pred

2000


array([117.25857981, 189.61517935, 175.14004939, ..., 193.65262491,
       150.23704872, 165.39968589])

In [17]:
print(X_test[:5])
print
print(Y_test[:5])
print
print(y_pred[:5])
print

[[60.62378116]
 [70.02471448]
 [68.1440328 ]
 [69.51564045]
 [71.61782407]]
[120.38257317 189.91196464 192.34397658 189.42507247 201.67935198]
[117.25857981 189.61517935 175.14004939 185.69696563 201.87693982]


<function print>

In [21]:
print("Test sample 0 : " , X_test[0])
print("Actual  : " , Y_test[0])
print("Predict : " , y_pred[0])

Test sample 0 :  [60.62378116]
Actual  :  120.382573166409
Predict :  117.25857981076689


In [22]:
lr.coef_ # W value

array([7.69674638])

In [24]:
lr.intercept_ #  b value

-349.3472884650804

In [26]:
lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

# Valuation metrics

In [27]:
lr.score(X_test , Y_test)

0.8568581848612943

In [28]:
from sklearn.datasets import load_boston

In [30]:
X ,Y = load_boston(return_X_y=True)

C:\Users\Qazi Moawiz\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dat

In [31]:
X.shape

(506, 13)

In [32]:
Y.shape

(506,)